files:
  - source: /app/assets/locales/locale-en.json
    translation: /app/assets/locales/locale-%two_letters_code%.json
  - source: /help/en/**/
    translation: /help/%two_letters_code%/**/%original_file_name%
